import { Product } from '@/types/product'

export const products: Product[] = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    image: '/expresso.png',
    tag: 'Tradicional',
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    image: '/americano.png',
    price: 9.9,
    tag: 'Tradicional',
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    image: '/expresso-cremoso.png',
    price: 9.9,
    tag: 'tradicional',
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    image: '/expresso-gelado.png',
    price: 9.9,
    tag: 'Gelado',
  },
  {
    id: 5,
    name: 'Café com leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    image: '/cafe-com-leite.png',
    price: 9.9,
    tag: 'Com leite',
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    image: '/latte.png',
    price: 9.9,
    tag: 'Com leite',
  },
  {
    id: 7,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    image: '/capuccino.png',
    price: 9.9,
    tag: 'Com leite',
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    image: '/macchiato.png',
    price: 9.9,
    tag: 'Com leite',
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    image: '/mochaccino.png',
    price: 9.9,
    tag: 'Com leite',
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    image: '/chocolate-quente.png',
    price: 9.9,
    tag: 'Com leite',
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    image: '/cubano.png',
    price: 9.9,
    tag: 'Alcoólico',
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    image: '/havaiano.png',
    price: 9.9,
    tag: 'Especial',
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    image: '/arabe.png',
    price: 9.9,
    tag: 'Especial',
  },
  {
    id: 14,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    image: '/irlandes.png',
    price: 9.9,
    tag: 'Alcoólico',
  },
]
